# Generated by Django 3.1.4 on 2020-12-31 21:08

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import readlater.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of article.', max_length=100, unique=True)),
                ('notes', models.CharField(blank=True, help_text='Notes about article.', max_length=100)),
                ('url', models.URLField(help_text='URL for article.', max_length=400)),
                ('priority', models.IntegerField(choices=[(400, 'Lower'), (300, 'Low'), (200, 'Normal'), (100, 'High'), (0, 'Higher')], default=200, help_text='Article priority.')),
                ('progress', models.IntegerField(default=0, help_text='Percentage progress reading article.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('added_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp for when article was added.')),
                ('finished_time', models.DateTimeField(blank=True, editable=False, help_text='Timestamp for when article was finished.', null=True)),
                ('updated_time', models.DateTimeField(blank=True, editable=False, help_text='Timestamp for when progress was updated.', null=True)),
                ('category', models.ForeignKey(help_text='Article category.', on_delete=models.SET(readlater.models.get_category_uncategorized), related_name='article', to='readlater.category')),
            ],
        ),
    ]
