# Generated by Django 3.1.4 on 2021-01-03 01:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name.', max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of article.', max_length=100, unique=True)),
                ('notes', models.CharField(blank=True, help_text='Notes about article.', max_length=100)),
                ('url', models.URLField(help_text='URL for article.', max_length=400)),
                ('priority', models.IntegerField(choices=[(400, 'Lower'), (300, 'Low'), (200, 'Normal'), (100, 'High'), (0, 'Higher')], default=200, help_text='Article priority.')),
                ('progress', models.IntegerField(default=0, help_text='Percentage progress reading article.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('added_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp for when article was added.')),
                ('finished_time', models.DateTimeField(blank=True, editable=False, help_text='Timestamp for when article was finished.', null=True)),
                ('updated_time', models.DateTimeField(blank=True, editable=False, help_text='Timestamp for when progress was updated.', null=True)),
                ('category', models.ForeignKey(blank=True, help_text='Article category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='readlater.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
