# Generated by Django 3.1.4 on 2020-12-21 21:09

from django.db import migrations

UNCATEGORIZED = 'Uncategorized'


def create_uncateg_record(apps, schema_editor):
    # see if 'Uncategorized' exists in Categories model and add if missing
    Category = apps.get_model('readlater', 'Category')
    uncat = Category.objects.filter(name=UNCATEGORIZED)
    if not uncat:
        uncat = Category(name=UNCATEGORIZED)
        uncat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('readlater', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_uncateg_record),
    ]
