# Generated by Django 3.1.4 on 2020-12-13 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readlater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Timestamp for when article was added.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='finished_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp for when article was finished.', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp for when progress was updated.', null=True),
        ),
    ]
