# Generated by Django 3.1.4 on 2020-12-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readlater', '0002_auto_20201221_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(help_text='Article category.', on_delete=models.SET(1), related_name='article', to='readlater.category'),
        ),
    ]
