# Generated by Django 3.1.4 on 2020-12-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readlater', '0002_auto_20201213_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(help_text='URL for article.'),
        ),
    ]
