# Generated by Django 3.1.4 on 2020-12-16 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readlater', '0003_auto_20201213_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(help_text='Article category.', on_delete=django.db.models.deletion.CASCADE, related_name='articvle', to='readlater.category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='finished_time',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp for when article was finished.', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(help_text='Name of article.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='rank',
            field=models.ForeignKey(editable=False, help_text='Article rank.', on_delete=django.db.models.deletion.CASCADE, related_name='article', to='readlater.rank'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_time',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp for when progress was updated.', null=True),
        ),
    ]
