# Generated by Django 3.1.4 on 2020-12-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readlater', '0004_auto_20201215_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rank',
            field=models.IntegerField(editable=False, help_text='Article rank.'),
        ),
    ]
