# Generated by Django 3.1.4 on 2020-12-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readlater', '0005_auto_20201217_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rank',
            field=models.IntegerField(editable=False, help_text='Article rank.', unique=True),
        ),
    ]
