# Generated by Django 3.1.4 on 2020-12-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readlater', '0006_auto_20201217_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='notes',
            field=models.CharField(blank=True, help_text='Notes about article.', max_length=100),
        ),
    ]
