# Generated by Django 3.1.4 on 2020-12-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readlater', '0008_auto_20201220_1159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
