# Generated by Django 3.1.4 on 2020-12-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readlater', '0009_delete_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='rank',
        ),
        migrations.AddField(
            model_name='article',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Lower'), (1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Higher')], default=2, help_text='Article priority.'),
        ),
    ]
