# Generated by Django 3.1.4 on 2020-12-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readlater', '0010_auto_20201221_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='priority',
            field=models.IntegerField(choices=[(400, 'Lower'), (300, 'Low'), (200, 'Normal'), (100, 'High'), (0, 'Higher')], default=200, help_text='Article priority.'),
        ),
    ]
