# Generated by Django 3.1.4 on 2020-12-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readlater', '0011_auto_20201221_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Lower'), (100, 'Low'), (200, 'Normal'), (300, 'High'), (400, 'Higher')], default=200, help_text='Article priority.'),
        ),
    ]
